name: Compile and deploy releases

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  compile-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: v16.13.1

      - name: Install dependencies
        run: yarn install

      - name: Install pkg
        run: yarn global add pkg

      - name: Compile
        run: yarn compile

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            wallet-generator-linux
            wallet-generator-macos
            wallet-generator-win.exe
          name: Wallet Generator ${{ steps.tag_version.outputs.new_tag }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
