name: Compile and deploy releases

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  compile-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: v16.13.1

      - name: Install dependencies
        run: yarn install

      - name: Install pkg
        run: yarn global add pkg

      - name: Compile
        run: yarn compile

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            wallet-generator-linux
            wallet-generator-macos
            wallet-generator-win.exe
